#!/bin/bash
xhost +local:

container_id=`docker ps -a | grep ros-kinetic-dev | awk '{print $1}'`
if [[ -z "$container_id" ]]; then
  docker run -it --net=host \
    --security-opt=seccomp:unconfined \
    --user=$(id -u) \
    -e DISPLAY=$DISPLAY \
    -e QT_GRAPHICSSYSTEM=native \
    -e CONTAINER_NAME=ros-kinetic-dev \
    -e USER=$USER \
    --workdir=/home/$USER \
    -v "/tmp/.X11-unix:/tmp/.X11-unix" \
    -v "/etc/group:/etc/group:ro" \
    -v "/etc/passwd:/etc/passwd:ro" \
    -v "/etc/shadow:/etc/shadow:ro" \
    -v "/etc/sudoers.d:/etc/sudoers.d:ro" \
    -v "/home/$USER/:/home/$USER/" \
    --device=/dev/dri:/dev/dri \
    --name=ros-kinetic-dev \
    brandeisrobotics/docker-ros:latest
else
  echo "Found container: $container_id"
  docker start $container_id
fi



